### ISSUE TITLE
3.43 The ledger page must show the date of the journal entry, a description column which is usually empty, a debit, a credit column, and a balance column.  The balance after each transaction and posting must be accurate;

### ISSUE THREAD

**Issue by matthewperiut** [matthewperiut/seven-elcounting#43] opened 2024-03-30 01:50 UTC

**Comment by slipperyfishy** [comment] 2024-04-11 18:29
Duplicate of 3.17 - closing this task out

**Closed as completed by slipperyfishy** 2024-04-11 18:29 UTC
